### ISSUE TITLE
Problems with timeout error handling

### ISSUE THREAD

**Issue by Rabsztok** [d4rky-pl/arboris#3]
Two problems:

Here, you have to access TIMEOUT not from an object `tracker` but from class `Tracker`:
https://github.com/d4rky-pl/arboris/blob/2523c85a8fab926a6a1a0fbd6980384ace84f027/src/index.js#L56

Second is about
https://github.com/d4rky-pl/arboris/blob/2523c85a8fab926a6a1a0fbd6980384ace84f027/src/index.js#L60
`tracker.unfinished()` returns `Map.iterator`, not an `Array`, so using `join` method here causes error.

**Comment by d4rky-pl** [comment]
Uh, thanks, they're leftovers from refactoring. Do you want to send a PR or are you OK with waiting for me to take care of this?

**Comment by d4rky-pl** [comment]
Sorry, I've misread, the first one is not an error. We're checking if the thrown error is a timeout from tracker to rethrow other exceptions if something else fails.

**Comment by Rabsztok** [comment]
#5

**Comment by d4rky-pl** [comment]
Fixed with #6
